<?php
// Build script: concatenates PHP files from src/ into a single dist/espresso.php
$srcDir = __DIR__ . '/src';
$destDir = __DIR__ . '/dist';
$destFile = $destDir . '/espresso.php';

$files = glob($srcDir . '/*.php');
if (!$files) {
    echo "No source files found in $srcDir\n";
    exit(1);
}

$header = "<?php\n";
$header .= "/**\n * Espresso - Single-file build\n * Generated by build.php\n */\n\n";
$header .= "declare(strict_types=1);\n\n";

$content = $header;

foreach ($files as $file) {
    $code = file_get_contents($file);
    // Remove opening <?php tag
    $code = preg_replace('/^\s*<\?php\s*/i', "", $code);
    // Remove duplicate declare(strict_types=1);
    $code = preg_replace('/declare\s*\(\s*strict_types\s*=\s*1\s*\)\s*;\s*/i', "", $code);

    // Append with a newline separator
    $content .= "\n// Source: " . basename($file) . "\n" . $code . "\n";
}

if (!is_dir($destDir)) {
    mkdir($destDir, 0755, true);
}

file_put_contents($destFile, $content);
chmod($destFile, 0644);

echo "Built: $destFile\n";
